stages:
  - build

build:windows:
  stage: build
  tags:
    - msvc
    - cmake
    - vcpkg
  cache:
    - key: "build-${CI_COMMIT_REF_SLUG}-${CI_CONCURRENT_ID}"
      paths:
        - build/
  before_script:
    - vcpkg install qtbase:x64-windows qtgrpc:x64-windows protobuf:x64-windows
    - cmake -B build -G "Visual Studio 17 2022" -A "x64" -DCMAKE_TOOLCHAIN_FILE="${ENV:VCPKG_ROOT}\scripts\buildsystems\vcpkg.cmake"
  script:
    - cmake --build build/ --config Release --parallel
